---
title: "Immunotherapy"
author: "Andreea Murariu"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#Installation of Packages edgeR, DESeq2, and ALDEx2
library(edgeR,quietly=T) 
library(DESeq2,quietly=T)
library(ALDEx2,quietly=T)
```

```{r}
#Setting the Working Directory
#andreea setting
## gg may comment this out 
setwd("/Users/andreeamurariu/Documents/github/3383-Project/")
getwd() 
```

```{r}
readCount<-read.table(file="data/GSE91061_raw_counts_GRCh38.p13_NCBI.tsv", header = T, skip=35, sep='\t', row.names = 1)
#pull out just the accession numbers and patient identifiers and put them in another file
d <- read.table(file="data/metadata.txt", header=F, row.names=1, sep='\t')
```

```{r}
#setting conditions for the dataset
conditions <- rep("Pre", 109)
grep("_On",d)
conditions[grep("_On",d)] <- "On"
conds <- data.frame(conditions)
conds$condition <- factor(conds$condition)
```


1) Using DESeq2 to identify differentially expressed genes (DEGs) in the Immunotherapy Dataset 

```{r}
# use edgeR filtering for rows as SOP
keep<-filterByExpr(readCount) 
read.keep <- readCount[keep,]

#Creating a DESeqDataSet
dds <- DESeqDataSetFromMatrix(countData = read.keep,colData = conds, design= ~condition) 

#DESeq2 analysis
deseq2out <- DESeq (dds) # use the default test
res <- results(deseq2out)
DESeq2::plotMA(res) # show the MA plot
#res
```

```{r}
#Random Permutation and Sampling
#1. Setting conditions
conds2 <- c(rep("Pre",5),rep("_On",5))
presampl <- which(conds2=="Pre")
onsampl <- which(conds2=="_On")

#Pulling a random sample, assigning it to a seed
set.seed(125)
random.pre <- sample(presampl,size = 5)
random.on <- sample(onsampl,size = 5)
groups.10 <- conds2[c(random.pre,random.on)]
df2.10 <- read.keep[,c(random.pre,random.on)]
groups.10.rand2 <- sample(groups.10)

#rerun DESeq2 with permuted data set - need to edit so that it works with DESeq2
dds2 <- DESeqDataSetFromMatrix(countData = df2.10,colData = groups.10.rand2, design= ~condition) ##edit this, attempt to set rownames 
deseq2outperm <- DESeq (dds) # use the default test
resperm <- results(deseq2outperm)
plotMA(resperm) # show the MA plot
resperm

#generating effect-size plots in DESeq2 - need to check how to make effect size plots here
lfcShrink(dds)

```

2) Using ALDEx2 to identify differentially expressed genes (DEGs) in the Immunotherapy Dataset 
ALDEx2 t-test and Wilcoxon rank-sum test
```{r}
#ALDEx2 code for differing gamma values (1e-3, 0.2, 0.5, 1)
read.keep <- readCount[keep,]
aldex.out <- aldex(read.keep, conditions, gamma=1e-3)
aldex.0.2 <- aldex(read.keep, conditions, gamma=0.2)
aldex.0.5 <- aldex(read.keep, conditions, gamma=0.5) 
aldex.1 <- aldex(read.keep, conditions, gamma=1) 

save(aldex.out, file="output/aldex.out.imm.Rda")
save(aldex.0.2, file="output/aldex.0.2.imm.Rda")
save(aldex.0.5, file="output/aldex.0.5.imm.Rda")
save(aldex.1, file="output/aldex.1.imm.Rda")

load(file="output/aldex.out.imm.Rda")
load(file="output/aldex.0.2.imm.Rda")
load(file="output/aldex.0.5.imm.Rda")
load(file="output/aldex.1.imm.Rda")

pdf("no-gamma.imm.pdf", height=5, width=7)
aldex.plot(aldex.out)

pdf("gamma0.2.imm.pdf", height=5, width=7)
aldex.plot(aldex.0.5)

pdf("gamma.0.5.imm.pdf", height=5, width=7)
aldex.plot(aldex.1)

pdf("gamma.1.imm.pdf", height=5, width=7)
aldex.plot(aldex.5)


#Generating graphs for Wilcoxon and t-tests - need to verify how to get 2 different effect size plots for each
aldex.out <- aldex(read.keep$effect, conditions,test="t",gamma=1e-3)
aldex.plot(aldex1e3wilc)

```


```{r}
#Random Permutation and Sampling
#1. Setting conditions
conds2 <- c(rep("Pre",5),rep("_On",5))
presampl <- which(conds2=="Pre")
onsampl <- which(conds2=="_On")

#Pulling a random sample, assigning it to a seed
set.seed(123)
random.pre <- sample(presampl,size = 5)
random.on <- sample(onsampl,size = 5)
groups.10 <- conds2[c(random.pre,random.on)]
df.10 <- read.keep[,c(random.pre,random.on)]
groups.10.rand <- sample(groups.10)

#ALDEX Running of data and effect size plot generation
aldexp1e-3<-aldex(df.10,groups.10,gamma=0.5)
aldex.plot(aldexoutp1e-3)
aldex.p.0.2 <- aldex(read.keep, r.conds, gamma=1)
aldex.plot(aldex.p.0.2)
aldex.p.0.5 <- aldex(read.keep, r.conds, gamma=0.5) 
aldex.plot(aldex.p.0.5)
aldex.p.1 <- aldex(read.keep, r.conds, gamma=1) 
aldex.plot(aldex.p.1)


#trying to generate a for loop for random permutations
for (x in 1:100) {
  random.pre <- sample(presampl,size = 5)
  random.on <- sample(onsampl,size = 5)
  groups.10 <- conds2[c(random.pre,random.on)]
  df.10 <- read.keep[,c(random.pre,random.on)]
  groups.10.rand <- sample(groups.10)
  loopedaldexperm <- aldex(df.10,groups.10,gamma=0.2)
  aldex.plot(loopedaldexperm)}
```

**TESTS**

```{r}
#------------------------ FDR CALCULATIONS FOR GAMMA=0.5,MU=0.15-------------------------------------
#baseline

gam <- aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = virginia.groups$groups.2)
aldexrun <- aldex(ko.virginia.filt,virginia.groups$groups.2,gamma=gam)
aldex.plot(aldexrun)

#---------------------------------------- For n=3 ----------------------------------------------------

PreG <- grep("Pre", )
OnG <- grep("_On", virginia.groups$groups.2)
refTP <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]
n.iter = 100
aldex.test.resultsa <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.5) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 5
condsa <- c(rep("Pre",5),rep("_On",5))
presampla <- which(conds2=="Pre")
onsampla <- which(conds2=="_On")
random.prea <- sample(presampl,size = 5)
random.ona <- sample(onsampl,size = 5)
groupsa <- conda[c(random.pre,random.on)]
dfa <- read.keep[,c(random.pre,random.on)]
groupsa.rand <- sample(groupsa)
aldexa<-aldex(dfa,groupsa,gamma=0.5)
aldex.plot(aldexa)
TP <- sum(sub.P %in% refTP)
FP <- sum(!(sub.P %in%refTP))
sen <- TP/length(refTP)
spec <- FP/length(sub.P)
aldex.test.results.3[i,] <- c(size,TP,FP, sen,spec)



aldex.p.0.2 <- aldex(read.keep, r.conds, gamma=1)
aldex.plot(aldex.p.0.2)
aldex.p.0.5 <- aldex(read.keep, r.conds, gamma=0.5) 
aldex.plot(aldex.p.0.5)
aldex.p.1 <- aldex(read.keep, r.conds, gamma=1) 
aldex.plot(aldex.p.1)


#trying to generate a for loop for random permutations
for (x in 1:100) {
  random.pre <- sample(presampl,size = 5)
  random.on <- sample(onsampl,size = 5)
  groups.10 <- conds2[c(random.pre,random.on)]
  df.10 <- read.keep[,c(random.pre,random.on)]
  groups.10.rand <- sample(groups.10)
  loopedaldexperm <- aldex(df.10,groups.10,gamma=0.2)
  aldex.plot(loopedaldexperm)}
```


```{r}








BV.ids <- grep("BV", virginia.groups$groups.2)
H.ids <- grep("Healthy", virginia.groups$groups.2)
refTP <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]
n.iter = 100
aldex.test.results.3 <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.3) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 3
sub.cond <- c(rep("H", size), rep("BV", size))
gam.sub <-  aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = sub.cond )
sub.ids <- c(sample(H.ids,size), sample(BV.ids,size))
sub.data <- ko.virginia.filt[,sub.ids]
aldex.sub <- aldex(sub.data,sub.cond,gamma=gam.sub)
sub.P <- rownames(aldex.sub)[which(abs(aldex.sub$effect) > 1)]
aldex.plot(aldex.sub)
# TP,FP, Sensitivity, and Specificity Calculations
TP <- sum(sub.P %in% refTP)
FP <- sum(!(sub.P %in%refTP))
sen <- TP/length(refTP)
spec <- FP/length(sub.P)
aldex.test.results.3[i,] <- c(size,TP,FP, sen,spec)
}
save(aldex.test.results.3, file="output/aldex.mu0.15.3.Rda")


#---------------------------------------- For n=5 ----------------------------------------------------

BV.ids5 <- grep("BV", virginia.groups$groups.2)
H.ids5 <- grep("Healthy", virginia.groups$groups.2)
refTP5 <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]

n.iter = 100
aldex.test.results.5 <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.5) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 5
sub.cond5 <- c(rep("H", size), rep("BV", size))
gam.sub5 <-  aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = sub.cond5 )
sub.ids5 <- c(sample(H.ids5,size), sample(BV.ids5,size))
sub.data5 <- ko.virginia.filt[,sub.ids5]
aldex.sub5 <- aldex(sub.data5,sub.cond5,gamma=gam.sub5)
sub5.P <- rownames(aldex.sub5)[which(abs(aldex.sub5$effect) > 1)]
aldex.plot(aldex.sub5)
# TP,FP, Sensitivity, and Specificity Calculations
TP5 <- sum(sub5.P %in% refTP5)
FP5 <- sum(!(sub5.P %in%refTP5))
sen5 <- TP5/length(refTP5)
spec5 <- FP5/length(sub5.P)
aldex.test.results.5[i,] <- c(size,TP5,FP5, sen5,spec5)
}
save(aldex.test.results.3, file="output/aldex.mu0.15.3.Rda")


#---------------------------------------- For n=10 ---------------------------------------------------

#labelling of each category
BV.ids10 <- grep("BV", virginia.groups$groups.2)
H.ids10 <- grep("Healthy", virginia.groups$groups.2)
refTP10 <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]

# matrix of results
n.iter = 100
aldex.test.results.10 <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.10) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 10
sub.cond10 <- c(rep("H", size), rep("BV", size))
gam.sub10 <-  aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = sub.cond10 )

sub.ids10 <- c(sample(H.ids10,size), sample(BV.ids10,size))
sub.data10 <- ko.virginia.filt[,sub.ids10]
aldex.sub10 <- aldex(sub.data10,sub.cond10,gamma=gam.sub10)
sub10.P <- rownames(aldex.sub10)[which(abs(aldex.sub10$effect) > 1)]
aldex.plot(aldex.sub10)

# TP,FP, Sensitivity, and Specificity Calculations
TP10 <- sum(sub10.P %in% refTP10)
FP10 <- sum(!(sub10.P %in%refTP10))
sen10 <- TP10/length(refTP10)
spec10 <- FP10/length(sub10.P)
aldex.test.results.10[i,] <- c(size,TP10,FP10,sen10,spec10)
}

#---------------------------------------- For n=20 ---------------------------------------------------

#labelling of each category
BV.ids20 <- grep("BV", virginia.groups$groups.2)
H.ids20 <- grep("Healthy", virginia.groups$groups.2)
refTP20 <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]

# matrix of results
n.iter = 100
aldex.test.results.20 <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.20) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 20
sub.cond20 <- c(rep("H", size), rep("BV", size))
gam.sub20 <-  aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = sub.cond20 )

sub.ids20 <- c(sample(H.ids20,size), sample(BV.ids20,size))
sub.data20 <- ko.virginia.filt[,sub.ids20]
aldex.sub20 <- aldex(sub.data20,sub.cond20,gamma=gam.sub20)
sub20.P <- rownames(aldex.sub20)[which(abs(aldex.sub20$effect) > 1)]
aldex.plot(aldex.sub20)

# TP,FP, Sensitivity, and Specificity Calculations
TP20 <- sum(sub20.P %in% refTP20)
FP20 <- sum(!(sub20.P %in%refTP20))
sen20 <- TP20/length(refTP20)
spec20 <- FP20/length(sub20.P)
aldex.test.results.20[i,] <- c(size,TP20,FP20,sen20,spec20)
}

#---------------------------------------- For n=50 ---------------------------------------------------

#labelling of each category
BV.ids50 <- grep("BV", virginia.groups$groups.2)
H.ids50 <- grep("Healthy", virginia.groups$groups.2)
refTP50 <- rownames(aldexrun)[which(abs(aldexrun$effect) > 1)]

# matrix of results
n.iter = 100

aldex.test.results.50 <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(aldex.test.results.50) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 50
sub.cond50 <- c(rep("H", size), rep("BV", size))
gam.sub50 <-  aldex.makeScaleMatrix(gamma=0.5, mu=c(0.15,0), conditions = sub.cond50 )

sub.ids50 <- c(sample(H.ids50,size), sample(BV.ids50,size))
sub.data50 <- ko.virginia.filt[,sub.ids50]
aldex.sub50 <- aldex(sub.data50,sub.cond50,gamma=gam.sub50)
sub50.P <- rownames(aldex.sub50)[which(abs(aldex.sub50$effect) > 1)]
aldex.plot(aldex.sub50)

# TP,FP, Sensitivity, and Specificity Calculations
TP50 <- sum(sub5.P %in% refTP50)
FP50 <- sum(!(sub5.P %in%refTP50))
sen50 <- TP50/length(refTP50)
spec50 <- FP50/length(sub50.P)
aldex.test.results.50[i,] <- c(size,TP50,FP50,sen50,spec50)
}


save(aldex.test.results.3, file="output/aldex.mu0.15.3.Rda")
save(aldex.test.results.5, file="output/aldex.mu0.15.5.Rda")
save(aldex.test.results.10, file="output/aldex.mu0.15.10.Rda")
save(aldex.test.results.20, file="output/aldex.mu0.15.20.Rda")
save(aldex.test.results.50, file="output/aldex.mu0.15.50.Rda")

load(file='output/aldex.mu0.15.3.Rda')
```


2. DESeq2

```{r}
##Baseline DESeq2##
conditions <- rep("Pre", 109)
grep("_On",d)
conditions[grep("_On",d)] <- "On"
conds <- data.frame(conditions)
conds$condition <- factor(conds$condition)
ddsa <- DESeqDataSetFromMatrix(countData = read.keep,colData = conds, design= ~condition)
deseq2outa <- DESeq (ddsa)
resa <- results(deseq2outa)
DESeq2::plotMA(resa)



####TRIALS
condsn <- c(rep("Pre",5),rep("_On",5))
presampln <- which(conds2=="Pre")
onsampln <- which(conds2=="_On")
random.pren <- sample(presampl,size = 5)
random.onn <- sample(onsampl,size = 5)
groupsn <- conds2[c(random.pre,random.on)]
dfn <- read.keep[,c(random.pre,random.on)]
groups.n.rand <- sample(groups.10)
aldexp0.5<-aldex(dfn,groupsn,gamma=0.5)
aldex.plot(aldexoutp0.5)
aldex.p.1 <- aldex(dfn,groupsn, gamma=1) 
aldex.plot(aldex.p.1)


#trying to generate a for loop for random permutations
for (x in 1:100) {
  random.pre <- sample(presampl,size = 5)
  random.on <- sample(onsampl,size = 5)
  groups.10 <- conds2[c(random.pre,random.on)]
  df.10 <- read.keep[,c(random.pre,random.on)]
  groups.10.rand <- sample(groups.10)
  loopedaldexperm <- aldex(df.10,groups.10,gamma=0.2)
  aldex.plot(loopedaldexperm)}


##loop for n=3
Pre.idda <- grep("Pre", d)
On.idda <- grep("_On", d)
refTPda <- rownames(resa)[which(abs(resa$padj) < 0.01)]
n.iter = 100
deseq2.test.resultsa <- matrix(data=NA, ncol=5, nrow=n.iter)
colnames(deseq2.test.resultsa) <- c("size", "TP", "FP","sens","spec")
for(i in 1:100){
size = 3
condsn <- c(rep("Pre",5),rep("_On",5))
presampln <- which(condsn=="Pre")
onsampln <- which(condsn=="_On")
random.pren <- sample(presampln,size = size)
random.onn <- sample(onsampln,size = size)
groupsn <- condsn[c(random.pren,random.onn)]
dfn <- read.keep[,c(random.pren,random.onn)]
groups.n.rand <- sample(groupsn)
sub.conddn <- data.frame(groupsn) # make a dataframe from the vector
sub.conddn$groupsn <- factor(sub.conddn$groupsn) # get the factors of the condition
sub.idsdn <- c(sample(presampln,size),sample(onsampln,size))
sub.datadn <- read.keep[,sub.idsdn]
ddsdn <- DESeqDataSetFromMatrix(countData = sub.datadn, colData = sub.conddn, design= ~groupsn)
resdn <- DESeq (ddsdn)
deseq2outdan <- results(resdn)
sub.deseqn <-rownames(deseq2outdan)[which(abs(deseq2outdan$padj) < 0.01)]
DESeq2::plotMA(resdn)

# TP,FP, Sensitivity, and Specificity Calculations
TPdn <- sum(sub.deseqn %in% refTPda)
FPdn <- sum(!(sub.deseqn %in%refTPda))
sendn <- TPdn/length(refTPda)
specdn <- FPdn/length(sub.deseqn)
deseq2.test.resultsa[i,] <- c(size,TPdn,FPdn,sendn,specdn)
}

save(deseq2.test.resultsa, file="output/deseq2.test.results.imm.Rda")

```


